In [1]:
import torch 
import numpy as np



In [2]:
#numpy转tensor
np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)

print(np_data,torch_data)

[[0 1 2]
 [3 4 5]] tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)


In [3]:
#tensor转numpy
tensorToarray = torch_data.numpy()
print(tensorToarray)

[[0 1 2]
 [3 4 5]]


In [4]:
#abs:绝对值
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)
print(
    '\nabs',
    '\nnumpy:',np.abs(data),
    '\ntorch:',torch.abs(tensor)
)


abs 
numpy: [1 2 1 2] 
torch: tensor([1., 2., 1., 2.])


In [6]:
#三角函数
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)
print(
    '\nsin',
    '\nnumpy:',np.mean(data),
    '\ntorch:',torch.mean(tensor)
)


sin 
numpy: 0.0 
torch: tensor(0.)


In [7]:
#矩阵相乘
data = [[1,2],[3,4]]
data = np.array(data)
tensor = torch.FloatTensor(data)

print(
    '\nnumpy:',np.matmul(data,data),#data.dot(data)
    '\ntorch:',torch.mm(tensor,tensor)
)