In [1]:
import torch
#自动求导
from torch.autograd import Variable



In [2]:
'''
深度学习的框架基于计算图谱（有向无环图），其中结点分为variable、常量、占位符等类型
variable中存放神经网络参数，在神经网络的优化中一般都是优化类型为variable的结点
将一个tensor作为一个神经网络的参数时，先转换为variable类型，才能反向传播计算且更新  
'''
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor,requires_grad=True)

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [3]:
t_out = torch.mean(tensor*tensor) #每个位置计算平方值再取平均
v_out = torch.mean(variable*variable)

print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [4]:
#tensor不能反向椽笔，variable可以反向传播
v_out.backward()
#反向传递的更新值,查看variable的梯度
print(variable.grad)

'''
梯度计算过程
v_out = 1/4 * sum(var*var)
d(v_out)/d(var) = 1/4 * 2 * variable = variable/2
'''



tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


'\nv_out = 1/4 * sum(var*var)\nd(v_out)/d(var) = 1/4 * 2 * variable = variable/2\n'

In [5]:
print(variable)
print(variable.data)
print(variable.data.numpy())

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
